Dashboard instructions (vibe-kanban 0c340b47)
The dashboard instructions are not good

==> Tapping localup/tap

Cloning into '/opt/homebrew/Library/Taps/localup/homebrew-tap'...

remote: Repository not found.

fatal: repository 'https://github.com/localup/homebrew-tap/' not found

Error: Failure while executing; ⁠ git clone https://github.com/localup/homebrew-tap /opt/homebrew/Library/Taps/localup/homebrew-tap --origin=origin --template= --config core.fsmonitor=false ⁠ exited with 128.

➜  \~

aswell as localup http 80 which is not a command

this is how you spin upo a client to go to a http relay

localup --relay=tunnel.kfs.es:4443  --port=3000 --token=$TOKEN --subdomain="usesend"

and this is for a tcp relay

localup --port=22  --relay=tunnel.kfs.es:5443 --protocol=tcp;

Also, make sure the dashboard shows a way to quickly create the token and replace the token to give the command for the JWT token

localup config set-token "jwt\_token"